- name: Добавить SSH key root
  become: true
  lineinfile:
    dest: ~/.ssh/authorized_keys
    line: "{{ ssh_key }}"
    create: yes

- name: Перезапустить ssh
  shell: systemctl restart ssh || systemctl restart sshd