- name: Проверить наличие папки .nvm
  become: no
  stat:
    path: "$HOME/.nvm"
  register: nvm_folder_check

- name: Получить версию уже установленного nvm
  become: no
  shell: >
    . "$HOME"/.nvm/nvm.sh && nvm -v
  register: nvm_version
  when: nvm_folder_check.stat.exists

- name: Версия уже установленного nvm совпадает
  become: no
  debug:
    msg: "nvm не установлен! уже имеется заданная версия: {{ nvm_version.stdout }}"
  when: 
    - nvm_version.stdout is defined
    - nvm_version.stdout == nvm_v

- name: Версия уже установленного nvm не совпадает
  become: no
  debug:
    msg: "nvm не установлен! уже имеется версия: {{ nvm_version.stdout }}"
  when: 
    - nvm_version.stdout is defined
    - nvm_version.stdout != nvm_v

- name: Установка nvm
  become: no
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v{{nvm_v}}/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "$HOME"
  when: not nvm_folder_check.stat.exists

- name: Получить версию установленного nvm
  become: no
  shell: >
    . "$HOME"/.nvm/nvm.sh && nvm -v
  register: new_nvm_version
  when: 
    - not nvm_version.stdout is defined

- name: Установлена версия nvm
  become: no
  debug:
    msg: "Установлен nvm версии: {{ new_nvm_version.stdout }}"
  when: 
    - not nvm_version.stdout is defined