# Удалить node 
# sudo apt-get purge --auto-remove nodejs

- name: Получаем версию
  command: node --version
  register: node_version
  ignore_errors: yes

- name: Версия уже установленного node совпадает
  become: no
  debug:
    msg: "node не установлен! уже имеется заданная версия: {{ node_version.stdout }}"
  when: 
    - node_version.changed and node_version.stdout[1:] == node_v

- name: Версия уже установленного node не совпадает
  become: no
  debug:
    msg: "node не установлен! уже имеется версия: {{ node_version.stdout }}"
  when: 
    - node_version.changed and node_version.stdout[1:] != node_v

- name: Установка ключей для node репозитория
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
  when: not node_version.changed

- name: Скачивание node и обновление пакетов
  apt_repository:
    # https://github.com/nodesource/distributions
    repo: "deb https://deb.nodesource.com/node_{{ node_v }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  when: not node_version.changed

- name: Устанавливаем node
  apt:
    name: nodejs
    state: present
  when: not node_version.changed

- name: Получаем версию
  command: node --version
  register: new_node_version
  ignore_errors: yes
  when: not node_version.changed

- name: Установлена версия node
  become: no
  debug:
    msg: "Установлен node версии: {{ new_node_version.stdout }}"
  when: not node_version.changed