all:
  hosts:
    192.168.1.155

# all:
#   hosts:
#     webserver1:
#       ansible_host: 192.168.1.101
#       ansible_user: your_username
#       ansible_ssh_pass: your_password
#       ansible_become_pass: your_sudo_password
#       some_custom_var: some_value
#     webserver2:
#       ansible_host: 192.168.1.102
#       ansible_user: your_username
#       ansible_ssh_pass: your_password
#       ansible_become_pass: your_sudo_password
#       another_custom_var: another_value

#   vars:
#     common_var1: common_value1
#     common_var2: common_value2

#   children:
#     webservers:
#       hosts:
#         webserver1:
#         webserver2:
#       vars:
#         webserver_var1: webserver_value1
#         webserver_var2: webserver_value2
