# https://habr.com/ru/companies/otus/articles/721166/
# https://docs.docker.com/engine/install/ubuntu/

# Задать пароль root на целевой машине sudo passwd root
# ansible-playbook ~/playbooks/ubuntu_install_docker.yaml -v --ask-pass --ask-become-pass

- name: Установка docker
  vars_prompt:
    - name: host
      prompt: "Введите host"
      private: false
    - name: user
      prompt: "Введите user"
      private: false
  hosts: "{{ host }}"
  become: true
  vars:
    ansible_user: "{{ user }}"
  tasks:
    - name: Обновить и установить пакеты
      include_tasks: ubuntu/tasks/upgrate_packages.yaml

    - name: Установить docker
      include_tasks: ubuntu/tasks/install_docker.yaml

    - name: Установить portainer
      include_tasks: ubuntu/tasks/install_portrainer.yaml