# Добавить в /etc/ansible/hosts.yaml
# Задать пароль root на целевой машине sudo passwd root
# ansible-playbook ~/playbooks/ubuntu_initial_setup.yaml

- name: Перовначальная настройка ubuntu
  hosts: 192.168.1.152
  become: true
  vars:
    ansible_become_pass: "qwerty"
    ansible_password: "qwerty"
    ansible_user: "app"
  tasks:
    - name: Обновить и установить пакеты
      include_tasks: ubuntu/tasks/upgrate_packages.yaml
    - name: Установить OpenSSH
      include_tasks: ubuntu/tasks/install_openssh.yaml
    - name: Добавить SSH publikkey пользователю
      vars:
        ssh_key: "ssh-rsa <Example SSH Key>"
      include_tasks: ubuntu/tasks/add_sshkey_from_user.yaml
    - name: Добавить SSH publikkey пользователю root
      vars:
        ssh_key: "ssh-rsa <Example SSH Key>"
      include_tasks: ubuntu/tasks/add_sshkey_from_root.yaml
    - name: Установить для root возможность входа
      include_tasks: ubuntu/tasks/set_permit_root_login.yaml
    # Доработать
    # - name: Установить zsh
    #   include_tasks: ubuntu/tasks/install_zsh.yaml